remindapp/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('remind/', include('remind.urls')), 
    path('', include('remind.urls')),  # remind アプリのURLを統合
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

remindapp/remind/urls.py
from django.contrib import admin
from django.urls import path
# from .views import HelloWorldClass
from .views import CustomLoginView, UserCreateView,CustomLogoutView,MenuView,MyitemsAdd,BoughtItem,ExtendItem
from . import views # 2025/1/31　うっちゃん追加
from django.contrib.auth import views as auth_views # 2025/1/31　うっちゃん追加

app_name = 'remind'

urlpatterns = [
    # path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path("signup/", UserCreateView.as_view(), name='signup'), # 2025/2/13 MANA追記
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/',CustomLogoutView.as_view(),name='logout'),
    # path('menu/', views.MenuView, name='menu'),
    path('menu/', MenuView.as_view(), name='menu'),
    path('myitems/add/', MyitemsAdd.as_view(), name='myitems-add'), # 2025/2/16 うっちゃん追記 新規登録画面
    path('settings/', views.settings_page, name='settings'),
    path('settings/default_term', views.update_default_term, name='default_term'),
    # 2/26　うっちゃん 手こずっているのでコメントアウト
    path('settings/reset_default_term/', views.reset_default_term, name='reset_default_term'),
    path('settings/change_personal_info/', views.change_personal_info, name='change_personal_info'),
    path('inquiry/',views.Inquiry,name='inquiry'),
    path('editmodal/', views.editmodal, name='editmodal'),
    path('bought-item/', BoughtItem.as_view(), name='bought-item'), 
    path('extend-item/', ExtendItem.as_view(), name='extend-item'),
    path('menu/delete', views.delete_item, name='delete-item'),
    path('menu/delete/item', views.delete, name='delete')
]

remindapp/templates/base-menu.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8"> <!--文字コードの指定-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Wasurenu{% endblock title%}</title>
    <meta name="description" content="ご自宅にある日用品や食品の在庫管理が簡単にできるWEBアプリです。">
    <meta property="og:sote_name" content="Wasurenu"> <!--共有時のサイト名をするタグ -->
    <meta property="og:site_name" content="Wasurenu"> <!--サイト名を指定するタグ-->
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Hachi+Maru+Pop&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon"> <!--ファビコンのURL-->
</head>
    <header>
        <div class="header-inner">
            {% block header %}Wasurenu{% endblock header %}
    
            <nav class="header-nav nav" id="js-nav">
                <ul class="nav__items nav-items">
                    <li class="nav-items__item"><a href="{% url 'remind:myitems-add' %}">新規物品登録</a></li>
                    <li class="nav-items__item"><a href="{% url 'remind:settings' %}">設定</a></li>
                    <li class="nav-items__item"><a href="{% url 'remind:logout' %}">ログアウト</a></li>
                    <li class="nav-items__item"><a href="{% url 'remind:inquiry' %}">お問い合わせ</a></li>
                </ul>
            </nav>

        <button class="header-hamburger hamburger" id="js-hamburger">
            <span></span>
            <span></span>
            <span></span>
        </button>
        </div>
    </header>
    {% block content %}
    {% endblock content %}
    <script src="{% static 'javascript/hamburger.js' %}"></script>
    <script src="{% static 'javascript/menu-sort.js' %}"></script>
    <script src="{% static 'javascript/modal.js' %}"></script>
    <script src="{% static 'javascript/date-edit-modal.js' %}"></script>
    <script src="{% static 'javascript/expire-date.js' %}"></script>
    <script src="{% static 'javascript/status.js' %}"></script>
    <script src="{% static 'javascript/tab-background.js' %}"></script>
</html>

remindapp/templates/base-setting.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8"> <!--文字コードの指定-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Wasurenu{% endblock title%}</title>
    <meta name="description" content="ご自宅にある日用品や食品の在庫管理が簡単にできるWEBアプリです。">
    <meta property="og:sote_name" content="Wasurenu"> <!--共有時のサイト名をするタグ -->
    <meta property="og:site_name" content="Wasurenu"> <!--サイト名を指定するタグ-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon"> <!--ファビコンのURL-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
    <header>
        <div>
            {% block header %}Wasurenu{% endblock header %}
        </div>
        <div class="home-button-container">
            <form action="/menu/">
                <button class="home-button" aria-label="ホームに戻る">
                    <span class="material-icons icon-size">home</span>
                </button>
            </form>
        </div>   
    </header>
    
    

    {% block content %}
    {% endblock content %}
    <script src="{% static 'javascript/hamburger.js' %}"></script>
    <script src="{% static 'javascript/count.js' %}"></script>
    <script src="{% static 'javascript/reset-modal.js' %}"></script>
    <script src="{% static 'javascript/personal-modal.js' %}"></script>
</html>

remindapp/templates/delete-item.html
{% extends 'base-menu.html' %}

{% block title %}メニュー削除画面{% endblock title %}


{% block content %}
<body>
    <div class="menu-container">
        <search class="search-container">
            <!-- <form action="./〇〇/{ **** }" method="POST">{% csrf_token %} actionにどこにデータを投げるか指定する。menuはユーザーごとに違う -->
                <form action="" method="POST">{% csrf_token %}
                    <!-- <input type="text" placeholder="管理物品の検索"> -->
                    <input type="text" placeholder="管理物品の検索" name="item_name" style="visibility: hidden;"
                    {% if new_regist_item %} value="{{ new_regist_item }}" {% endif %}>
                <button type="submit" style="visibility: hidden;">登録</button>    
            </form>
            <!-- うっちゃん追加 -->
            {% if error_message %}
                <p class="error">{{ error_message }}</p>
            {% endif %}               
        </search>
        
        <div class="transition-container">
            <a href="{% url 'remind:menu' %}">戻る</a>
        </div>
    
        <div>
            <!-- <form action="" method="GET" class="list-container"> -->
            <div class="list-container">
                <div>管理物品一覧</div>
                <!-- <button type="submit" id="sort-next-purchase" name="sort" 
                value="sort-next-purchase{{ sort_symbols.sort_next_purchase.0 }}">次回購入日順{{ sort_symbols.sort_next_purchase.1 }}</button>
                <button type="submit" id="sort-recent-purchase" name="sort" 
                value="sort-recent-purchase{{ sort_symbols.sort_recent_purchase.0 }}">最近買った順{{ sort_symbols.sort_recent_purchase.1 }}</button> -->
                <button id="sort-next-purchase">次回購入期限順</button>
                <button id="sort-recent-purchase">最近買った順</button>
            </div>
            <!-- </form> -->
            <div>

            </div>
            
            <div class="tabs">
            
                {% if not tab_label %}
                <input type="radio" id="all" name="tab-label" checked>
                {% elif tab_label == "all" %}
                <input type="radio" id="all" name="tab-label" checked>
                {% else %}
                <input type="radio" id="all" name="tab-label">
                {% endif %}
                <label class="tab-label" for="all">ALL</label>
            
                {% if tab_label == "daily-item" %}
                <input type="radio" id="daily-item" name="tab-label" checked>
                {% else %}
                <input type="radio" id="daily-item" name="tab-label">
                {% endif %}
                <label class="tab-label" for="daily-item">日用品</label>
            
                {% if tab_label == "food" %}
                <input type="radio" id="food" name="tab-label" checked>
                {% else %}
                <input type="radio" id="food" name="tab-label">
                {% endif %}
                <label class="tab-label" for="food">食品</label>
            
                {% if tab_label == "others" %}
                <input type="radio" id="others" name="tab-label" checked>
                {% else %}
                <input type="radio" id="others" name="tab-label">
                {% endif %}
                <label class="tab-label" for="others">その他</label>
        
                
                <div  class="tab-content" id="all-content">
                     <!--以下バックエンドに値に置き換える-->
                     {% for goods in goods_items %}
                    <div class="item">
                        <div>
                            <!-- <p id="purchase-status-{{ goods.id }}" class="purchase-status">〇</p> -->
                            <!-- <p>{{ goods.goods_name }}</p><br> 2/24 うっちゃん追加 -->
                            <p class="js-modal-open" data-target="all-modal-{{ goods.id }}" data-expire-date="{{ goods.expire_date|date:'Y-m-d' }}">{{ goods.goods_name }}</p><br> <!--ALLのリスト-->
                            <!-- 2/24　うっちゃん削除 -->
                            <!-- <span data-key="purchase_date">購入日 {{ goods.purchase_date|date:"Y/m/d" }}</span><br> -->
                            <!-- <span data-key="next_purchase_date">次回購入予定 {{ goods.next_purchase_date|date:"Y/m/d" }}</span> -->
                            <span data-key="purchase_date">購入日：{{ goods.purchase_date|date:"Y/m/d" }}</span><br>
                            <span data-key="next_purchase_date">次回購入予定：{{ goods.next_purchase_date|date:"Y/m/d" }}</span>
                            {% include 'menu-modal.html' %}
                            </div>
                        <div>
                            <!-- 2/24　うっちゃん追加 -->                            
                            <form action="{% url 'remind:delete' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="item_name" value="{{ goods.goods }}">
                                <input type="hidden" name="item_id" value="{{ goods.id }}">
                                <input type="hidden" name="tab_label" value="all">
                                <button type="submit">削除</button>
                            </form>

                        </div>      
                    </div>
                    {% endfor %}
                </div>
                <div class="tab-content" id="daily-content">
                    {% for d_goods in daily_goods %}
                    <div class="item">
                        <div>
                            <p class="js-modal-open" data-target="daily-modal-{{ d_goods.id }}">{{ d_goods.goods_name }}</p><br> <!--日用品のリスト-->
                            <span data-key="purchase_date">購入日：{{ d_goods.purchase_date|date:"Y/m/d" }}</span><br>
                            <span data-key="next_purchase_date">次回購入予定：{{ d_goods.next_purchase_date|date:"Y/m/d" }}</span>
                            {% include 'menu-modal.html' %}
                            </div>
                        <div>
                            <!-- 2/24　うっちゃん追加 -->                            
                            <form action="{% url 'remind:delete' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="item_name" value="{{ goods.goods }}">
                                <input type="hidden" name="item_id" value="{{ d_goods.id }}">
                                <input type="hidden" name="tab_label" value="daily-item">
                                <button type="submit">削除</button>
                            </form>
                        </div>      
                    </div>
                    {% endfor %}
                </div>
                <div class="tab-content" id="food-content">
                    {% for f_goods in food_goods %}
                    <div class="item">
                        <div>
                            <p class="js-modal-open" data-target="food-modal-{{ f_goods.id }}" data-expire-date="{{ f_goods.expire_date|date:'Y-m-d' }}">{{ f_goods.goods_name }}</p><br> <!--食品のリスト-->
                            <span data-key="purchase_date">購入日：{{ f_goods.purchase_date|date:"Y/m/d" }}</span><br>
                            <span data-key="next_purchase_date">次回購入予定：{{ f_goods.next_purchase_date|date:"Y/m/d" }}</span>
                            {% include 'menu-modal.html' %}
                            </div>
                        <div>
                            <!-- 2/24　うっちゃん追加 -->                            
                            <form action="{% url 'remind:delete' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="item_name" value="{{ goods.goods }}">
                                <input type="hidden" name="item_id" value="{{ f_goods.id }}">
                                <input type="hidden" name="tab_label" value="food">
                                <button type="submit">削除</button>
                            </form>
                        </div>      
                    </div>
                    {% endfor %}
                </div>
                <div class="tab-content" id="others-content">
                   {% for o_goods in other_goods %}
                    <div class="item">
                        <div>
                            <p class="js-modal-open" data-target="other-modal-{{ o_goods.id }}">{{ o_goods.goods_name }}</p><br> <!--その他のリスト-->
                            <span data-key="purchase_date">購入日：{{ o_goods.purchase_date|date:"Y/m/d" }}</span><br>
                            <span data-key="next_purchase_date">次回購入予定：{{ o_goods.next_purchase_date|date:"Y/m/d" }}</span>
                            {% include 'menu-modal.html' %}
                            </div>
                        <div>
                            <!-- 2/24　うっちゃん追加 -->                            
                            <form action="{% url 'remind:delete' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="item_name" value="{{ goods.goods }}">
                                <input type="hidden" name="item_id" value="{{ o_goods.id }}">
                                <input type="hidden" name="tab_label" value="others">
                                <button type="submit">削除</button>
                            </form>
                        </div>      
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
  
</body>

{% endblock content %}

remindapp/templates/menu.html
{% extends 'base-menu.html' %}

{% block title %}メニュー画面{% endblock title %}


{% block content %}
<body>
    <div class="menu-container">
        <search class="search-container">
            <!-- <form action="./〇〇/{ **** }" method="POST">{% csrf_token %} actionにどこにデータを投げるか指定する。menuはユーザーごとに違う -->
                <form action="" method="POST">{% csrf_token %}
                    <!-- <input type="text" placeholder="管理物品の検索"> -->
                    <input type="text" placeholder="管理物品の検索" name="item_name"
                    {% if new_regist_item %} value="{{ new_regist_item }}" {% endif %}>
                <button type="submit">登録</button>    
            </form>
            <!-- うっちゃん追加 -->
            {% if error_message %}
                <p class="error">{{ error_message }}</p>
            {% endif %}               
        </search>

        <div class="transition-container">
            <a href="{% url 'remind:delete-item' %}">選択削除</a>
        </div>
    
        <div>
            <!-- <form action="" method="GET" class="list-container"> -->
            <div class="list-container">
                <div>管理物品一覧</div>
                <!-- <button type="submit" id="sort-next-purchase" name="sort" 
                value="sort-next-purchase{{ sort_symbols.sort_next_purchase.0 }}">次回購入日順{{ sort_symbols.sort_next_purchase.1 }}</button>
                <button type="submit" id="sort-recent-purchase" name="sort" 
                value="sort-recent-purchase{{ sort_symbols.sort_recent_purchase.0 }}">最近買った順{{ sort_symbols.sort_recent_purchase.1 }}</button> -->
                <button id="sort-next-purchase">次回購入期限順</button>
                <button id="sort-recent-purchase">最近買った順</button>
            </div>
            <!-- </form> -->
            <div>

            </div>
            
            <div class="tabs">
            
                {% if not tab_label %}
                <input type="radio" id="all" name="tab-label" checked>
                {% elif tab_label == "all" %}
                <input type="radio" id="all" name="tab-label" checked>
                {% else %}
                <input type="radio" id="all" name="tab-label">
                {% endif %}
                <label class="tab-label" for="all">ALL</label>
            
                {% if tab_label == "daily-item" %}
                <input type="radio" id="daily-item" name="tab-label" checked>
                {% else %}
                <input type="radio" id="daily-item" name="tab-label">
                {% endif %}
                <label class="tab-label" for="daily-item">日用品</label>
            
                {% if tab_label == "food" %}
                <input type="radio" id="food" name="tab-label" checked>
                {% else %}
                <input type="radio" id="food" name="tab-label">
                {% endif %}
                <label class="tab-label" for="food">食品</label>
            
                {% if tab_label == "others" %}
                <input type="radio" id="others" name="tab-label" checked>
                {% else %}
                <input type="radio" id="others" name="tab-label">
                {% endif %}
                <label class="tab-label" for="others">その他</label>
        
                
                <div  class="tab-content" id="all-content">
                     <!--以下バックエンドに値に置き換える-->
                     {% for goods in goods_items %}
                    <div class="item">
                        <div>
                            <!-- <p id="purchase-status-{{ goods.id }}" class="purchase-status">〇</p> -->
                            <!-- <p>{{ goods.goods_name }}</p><br> 2/24 うっちゃん追加 -->
                            <p class="js-modal-open" data-target="all-modal-{{ goods.id }}" data-expire-date="{{ goods.expire_date|date:'Y-m-d' }}">{{ goods.goods_name }}</p><br> <!--ALLのリスト-->
                            <!-- 2/24　うっちゃん削除 -->
                            <!-- <span data-key="purchase_date">購入日 {{ goods.purchase_date|date:"Y/m/d" }}</span><br> -->
                            <!-- <span data-key="next_purchase_date">次回購入予定 {{ goods.next_purchase_date|date:"Y/m/d" }}</span> -->
                            <span data-key="purchase_date">購入日：{{ goods.purchase_date|date:"Y/m/d" }}</span><br>
                            <span data-key="next_purchase_date">次回購入予定：{{ goods.next_purchase_date|date:"Y/m/d" }}</span>
                            {% include 'menu-modal.html' %}
                            </div>
                        <div>
                            <!-- 2/24　うっちゃん追加 -->                            
                            <form action="{% url 'remind:bought-item' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="item_id" value="{{ goods.id }}">
                                <input type="hidden" name="tab_label" value="all">
                                <button type="submit">買った</button>
                            </form>
                        
                            <form action="{% url 'remind:extend-item' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="item_id" value="{{ goods.id }}">
                                <input type="hidden" name="tab_label" value="all">
                                <button type="submit">延長</button>
                            </form> 
                        </div>      
                    </div>
                    {% endfor %}
                </div>
                <div class="tab-content" id="daily-content">
                    {% for d_goods in daily_goods %}
                    <div class="item">
                        <div>
                            <p class="js-modal-open" data-target="daily-modal-{{ d_goods.id }}">{{ d_goods.goods_name }}</p><br> <!--日用品のリスト-->
                            <span data-key="purchase_date">購入日：{{ d_goods.purchase_date|date:"Y/m/d" }}</span><br>
                            <span data-key="next_purchase_date">次回購入予定：{{ d_goods.next_purchase_date|date:"Y/m/d" }}</span>
                            {% include 'menu-modal.html' %}
                            </div>
                        <div>
                            <!-- 2/24　うっちゃん追加 -->                            
                            <form action="{% url 'remind:bought-item' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="item_id" value="{{ d_goods.id }}">
                                <input type="hidden" name="tab_label" value="daily-item">
                                <button type="submit">買った</button>
                            </form>
                        
                            <form action="{% url 'remind:extend-item' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="item_id" value="{{ d_goods.id }}">
                                <input type="hidden" name="tab_label" value="daily-item">
                                <button type="submit">延長</button>
                            </form> 
                        </div>      
                    </div>
                    {% endfor %}
                </div>
                <div class="tab-content" id="food-content">
                    {% for f_goods in food_goods %}
                    <div class="item">
                        <div>
                            <p class="js-modal-open" data-target="food-modal-{{ f_goods.id }}" data-expire-date="{{ f_goods.expire_date|date:'Y-m-d' }}">{{ f_goods.goods_name }}</p><br> <!--食品のリスト-->
                            <span data-key="purchase_date">購入日：{{ f_goods.purchase_date|date:"Y/m/d" }}</span><br>
                            <span data-key="next_purchase_date">次回購入予定：{{ f_goods.next_purchase_date|date:"Y/m/d" }}</span>
                            {% include 'menu-modal.html' %}
                            </div>
                        <div>
                            <!-- 2/24　うっちゃん追加 -->                            
                            <form action="{% url 'remind:bought-item' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="item_id" value="{{ f_goods.id }}">
                                <input type="hidden" name="tab_label" value="food">
                                <button type="submit">買った</button>
                            </form>
                        
                            <form action="{% url 'remind:extend-item' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="item_id" value="{{ f_goods.id }}">
                                <input type="hidden" name="tab_label" value="food">
                                <button type="submit">延長</button>
                            </form>
                        </div>      
                    </div>
                    {% endfor %}
                </div>
                <div class="tab-content" id="others-content">
                   {% for o_goods in other_goods %}
                    <div class="item">
                        <div>
                            <p class="js-modal-open" data-target="other-modal-{{ o_goods.id }}">{{ o_goods.goods_name }}</p><br> <!--その他のリスト-->
                            <span data-key="purchase_date">購入日：{{ o_goods.purchase_date|date:"Y/m/d" }}</span><br>
                            <span data-key="next_purchase_date">次回購入予定：{{ o_goods.next_purchase_date|date:"Y/m/d" }}</span>
                            {% include 'menu-modal.html' %}
                            </div>
                        <div>
                            <!-- 2/24　うっちゃん追加 -->                            
                            <form action="{% url 'remind:bought-item' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="item_id" value="{{ o_goods.id }}">
                                <input type="hidden" name="tab_label" value="others">
                                <button type="submit">買った</button>
                            </form>
                        
                            <form action="{% url 'remind:extend-item' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="item_id" value="{{ o_goods.id }}">
                                <input type="hidden" name="tab_label" value="others">
                                <button type="submit">延長</button>
                            </form>
                        </div>      
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
  
</body>

{% endblock content %}

remindapp/templates/personal-info-modal.html
<!-- モーダル本体 -->
<div class="modal" id="js-personal-modal">
    <div class="modal-container">
      <!-- モーダルを閉じるボタン -->
      <div class="modal-close" id="js-personal-modal-close">×</div>
      <!-- モーダル内部のコンテンツ -->
      <div class="personal-modal-content">
          <div>
            <form action="{% url 'remind:change_personal_info' %}" method="POST">{% csrf_token %}
              <p>ログイン情報変更</p>
              <div class="personal">
                <label for="E-mail">メールアドレス</label>
                <input type="email" id="E-mail" name="email" value="{{ before_mailaddress }}"> 
                <label for="password">パスワード</label>
                <input type="password" id="password" name="password" placeholder=" 変更後のパスワード">
                <label for="password">確認用パスワード</label>
                <input type="password" id="confirm_password" name="confirm_password" placeholder=" パスワード確認用">
              </div>
              <button type="submit">変更する</button>
            </form>
          </div>
      </div>
    </div>
  </div>

remindapp/templates/reset-modal.html
<!-- モーダル本体 -->
<div class="modal" id="js-reset-modal">
    <div class="modal-container">
      <!-- モーダルを閉じるボタン -->
      <div class="modal-close" id="js-reset-modal-close">×</div>
      <!-- モーダル内部のコンテンツ -->
      <div class="reset-modal-content">
            <div>
              <span>次回購入までの期間を</span><br>
              <span>初期化しますか？</span>
            </div>
             <!--ALLのリスト-->
             <div>
              <form action="{% url 'remind:reset_default_term' %}" method="POST">{% csrf_token %}
                <input type="hidden" name="default_term" value="0">
                <input type="hidden" name="○○" value="○○">                
                <button type="submit">初期化</button>
              </form>
                <button type="submit">しない</button>
            </div>
      </div>
    </div>
  </div>

remindapp/templates/setting.html
{% extends 'base-setting.html' %}
{% load static %}

{% block customcss %}
<link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock customcss %}

{% block title %}設定{% endblock title %}


{% block content %}
<body>
    <div class="setting-container">
            <form action="{% url 'remind:default_term' %}" method="POST"> {% csrf_token %} <!--actionにどこにデータを投げるか指定する。menuはユーザーごとに違う -->
                <label>次回購入までの期間の一括設定</label>
                <div class="default-period">
                    <button type="button" id="js-decrement">-</button>
                    <span class="count">0</span>
                    <button type="button" id="js-increment">+</button> 
                    <input type="hidden" name="default_term" value="0"> 
                    <!-- <input type="number" name="default_term" min="0" value="0"> --> <!-- MANA追記：JSではないやり方でとりあえず -->
                    <small>週間後</small>
                </div>
                <button type="submit">期間登録</button> <!-- 2025/2/15 MANA追記　-->             
            </form> 
        <div>
            <form action="" method="POST">
                <label for="alert">通知設定</label>
                <select name="week" id="alert">
                    <option value="">通知する曜日を入力</option>
                    <option value="1">月曜日</option>
                    <option value="2">火曜日</option>
                    <option value="3">水曜日</option>
                    <option value="4">木曜日</option>
                    <option value="5">金曜日</option>
                    <option value="6">土曜日</option>
                    <option value="7">日曜日</option>
                    <option value="8">毎日</option>
                </select>
            </form>      
        </div>
        <div>
            <div>
                <label for="">期間初期化</label>
                <button id="js-reset-modal-open" type="button">次回購入までの期間を初期化</button>
                {% include 'reset-modal.html' %}
            </div>
        </div>
        <div>
            <div>
                <label for="">メールアドレス・パスワードの変更</label> <!--モーダル-->
                <button id="js-personal-modal-open" type="button">変更する</button>   
                {% include 'personal-info-modal.html' with before_mailaddress=before_mailaddress %}  
            </div>
        </div>
    </div>
</body>

{% endblock content %}